"""
api.py
-------
FastAPI backend for the UCLA Study Spot Recommender.

Endpoints:
  GET  /health              — liveness check
  GET  /ready               — readiness check (confirms model is loaded)
  GET  /stats               — request counts and usage metrics
  GET  /spots               — all 30 spots (for map/browse view)
  POST /recommend           — returns top-N recommendations given user prefs
  POST /recommend/explain   — per-feature contribution for a named spot + prefs

Run:
  uvicorn api:app --reload --port 8000

Docs (auto-generated by FastAPI):
  http://localhost:8000/docs   — Swagger UI
  http://localhost:8000/redoc  — ReDoc
"""

import json
import logging
import time
from collections import defaultdict
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

# ---------------------------------------------------------------------------
# Logging — writes to stdout so Cloud Run picks it up automatically
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR  = Path(__file__).resolve().parent
DATA_JSON = BASE_DIR / "data" / "raw" / "ucla" / "all_spots.json"
ENG_CSV   = BASE_DIR / "tables" / "engineered_df.csv"

# ---------------------------------------------------------------------------
# Feature columns (must match model script exactly)
# ---------------------------------------------------------------------------

FEATURE_COLS = [
    "has_wifi", "has_outlets", "has_coffee", "has_food",
    "feat_quiet", "feat_outdoor", "feat_comfortable_seating",
    "feat_shaded", "feat_benches", "feat_tables",
    "feat_group_friendly", "feat_printing_nearby", "feat_natural_light",
    "weather_dependent", "is_indoor", "is_outdoor",
    "comfort_score", "connectivity_score", "group_score",
    "outdoor_score", "amenity_score", "noise_encoded",
]

FEATURE_LABELS = {
    "has_wifi":                "Has WiFi",
    "has_outlets":             "Has Outlets",
    "has_coffee":              "Has Coffee",
    "has_food":                "Has Food",
    "feat_quiet":              "Quiet Environment",
    "feat_outdoor":            "Outdoor Setting",
    "feat_comfortable_seating":"Comfortable Seating",
    "feat_shaded":             "Shaded Area",
    "feat_benches":            "Benches Available",
    "feat_tables":             "Tables Available",
    "feat_group_friendly":     "Group Friendly",
    "feat_printing_nearby":    "Printing Nearby",
    "feat_natural_light":      "Natural Light",
    "weather_dependent":       "Weather Dependent",
    "is_indoor":               "Indoor Space",
    "is_outdoor":              "Outdoor Space",
    "comfort_score":           "Comfort Score",
    "connectivity_score":      "Connectivity Score",
    "group_score":             "Group Study Score",
    "outdoor_score":           "Outdoor Quality Score",
    "amenity_score":           "Amenity Score",
    "noise_encoded":           "Noise Level (0=silent)",
}

# ---------------------------------------------------------------------------
# Request counters — in-memory, resets on restart
# ---------------------------------------------------------------------------

_counters: dict = defaultdict(int)
_start_time: float = time.time()

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------

class UserPrefs(BaseModel):
    wants_wifi:        int = Field(1, ge=0, le=1,  description="Needs WiFi (0/1)")
    wants_outlets:     int = Field(0, ge=0, le=1,  description="Needs outlets (0/1)")
    wants_coffee:      int = Field(0, ge=0, le=1,  description="Wants coffee (0/1)")
    wants_food:        int = Field(0, ge=0, le=1,  description="Wants food (0/1)")
    wants_quiet:       int = Field(0, ge=0, le=1,  description="Needs quiet (0/1)")
    wants_outdoor:     int = Field(0, ge=0, le=1,  description="Prefers outdoor (0/1)")
    wants_group:       int = Field(0, ge=0, le=1,  description="Group study (0/1)")
    wants_comfortable: int = Field(0, ge=0, le=1,  description="Comfortable seating (0/1)")
    weather_ok:        int = Field(1, ge=0, le=1,  description="OK with weather risk (0/1)")
    noise_tolerance:   int = Field(2, ge=0, le=4,  description="Noise tolerance 0=silent 4=loud")
    connectivity_need: int = Field(1, ge=0, le=3,  description="Connectivity priority 0-3")
    n_results:         int = Field(3, ge=1, le=10, description="How many results to return")


class ExplainRequest(BaseModel):
    spot_name: str
    prefs:     UserPrefs


class SpotResult(BaseModel):
    rank:        int
    name:        str
    category:    str
    similarity:  float
    description: Optional[str] = None
    noise_level: Optional[str] = None
    features:    list[str]     = []
    best_times:  list[str]     = []
    avoid_times: list[str]     = []
    url:         Optional[str] = None
    hours:       Optional[str] = None
    hours_note:  Optional[str] = None
    building:    Optional[str] = None
    area:        Optional[str] = None
    lat:         Optional[float] = None
    lng:         Optional[float] = None
    food_nearby: Optional[str] = None
    access:      Optional[str] = None


class FeatureContrib(BaseModel):
    feature:      str
    user_value:   float
    spot_value:   float
    rf_weight:    float
    contribution: float


class RecommendResponse(BaseModel):
    results:         list[SpotResult]
    query_vector:    dict[str, float]
    latency_ms:      float


class ExplainResponse(BaseModel):
    spot_name:     str
    contributions: list[FeatureContrib]


class StatsResponse(BaseModel):
    uptime_seconds:      float
    total_requests:      int
    recommend_calls:     int
    explain_calls:       int
    spots_calls:         int
    spots_loaded:        int


# ---------------------------------------------------------------------------
# Recommender
# ---------------------------------------------------------------------------

class Recommender:
    def __init__(self):
        self.df:           pd.DataFrame | None = None
        self.Xs:           np.ndarray  | None = None
        self.Xw:           np.ndarray  | None = None
        self.scaler:       MinMaxScaler | None = None
        self.weights:      np.ndarray  | None = None
        self.rf:           RandomForestClassifier | None = None
        self.spots_lookup: dict = {}

    def load(self):
        logger.info("Loading engineered features from %s", ENG_CSV)
        eng = pd.read_csv(ENG_CSV)
        eng["noise_encoded"] = eng["noise_encoded"].fillna(eng["noise_encoded"].median())
        self.df = eng.reset_index(drop=True)

        X = eng[FEATURE_COLS].astype(float).values
        self.scaler = MinMaxScaler()
        self.Xs = self.scaler.fit_transform(X)

        logger.info("Training Random Forest for feature weighting...")
        self.rf = RandomForestClassifier(
            n_estimators=300, random_state=42, class_weight="balanced"
        )
        self.rf.fit(self.Xs, eng["category"])
        self.weights = self.rf.feature_importances_
        self.Xw = self.Xs * self.weights

        logger.info("Loading spot display data from %s", DATA_JSON)
        raw = json.loads(DATA_JSON.read_text(encoding="utf-8"))
        self.spots_lookup = {s["name"]: s for s in raw}

        logger.info("Recommender ready — %d spots loaded", len(self.df))
        return self

    def _build_query_vector(self, p: UserPrefs) -> np.ndarray:
        v = {
            "has_wifi":                float(p.wants_wifi),
            "has_outlets":             float(p.wants_outlets),
            "has_coffee":              float(p.wants_coffee),
            "has_food":                float(p.wants_food),
            "feat_quiet":              float(p.wants_quiet),
            "feat_outdoor":            float(p.wants_outdoor),
            "feat_comfortable_seating":float(p.wants_comfortable),
            "feat_shaded":             float(p.wants_outdoor),
            "feat_benches":            float(p.wants_outdoor),
            "feat_tables":             float(p.wants_group),
            "feat_group_friendly":     float(p.wants_group),
            "feat_printing_nearby":    0.0,
            "feat_natural_light":      float(p.wants_outdoor * 0.5),
            "weather_dependent":       float(p.weather_ok),
            "is_indoor":               float(1 - p.wants_outdoor),
            "is_outdoor":              float(p.wants_outdoor),
            "comfort_score":           float(p.wants_comfortable * 2 + p.wants_quiet),
            "connectivity_score":      float(p.connectivity_need),
            "group_score":             float(p.wants_group * 2),
            "outdoor_score":           float(p.wants_outdoor * 3),
            "amenity_score":           float(p.wants_wifi + p.wants_outlets
                                             + p.wants_coffee + p.wants_food),
            "noise_encoded":           float(p.noise_tolerance),
        }
        return np.array([v[c] for c in FEATURE_COLS])

    def recommend(self, prefs: UserPrefs) -> tuple[list[dict], dict]:
        qv  = self._build_query_vector(prefs)
        qvs = self.scaler.transform(qv.reshape(1, -1))
        qvw = qvs * self.weights

        sims    = cosine_similarity(qvw, self.Xw)[0]
        top_idx = np.argsort(sims)[::-1][: prefs.n_results]

        results = []
        for rank, idx in enumerate(top_idx, 1):
            name = self.df.iloc[idx]["name"]
            raw  = self.spots_lookup.get(name, {})
            results.append({
                "rank":        rank,
                "name":        name,
                "category":    self.df.iloc[idx]["category"],
                "similarity":  round(float(sims[idx]), 4),
                "description": raw.get("description"),
                "noise_level": raw.get("noise_level"),
                "features":    raw.get("features") or [],
                "best_times":  raw.get("best_times") or [],
                "avoid_times": raw.get("avoid_times") or [],
                "url":         raw.get("url"),
                "hours":       raw.get("hours"),
                "hours_note":  raw.get("hours_note"),
                "building":    raw.get("building"),
                "area":        raw.get("area"),
                "lat":         raw.get("lat"),
                "lng":         raw.get("lng"),
                "food_nearby": raw.get("food_nearby"),
                "access":      raw.get("access"),
            })

        query_vector = {
            FEATURE_LABELS[c]: round(float(qvs[0][i]), 3)
            for i, c in enumerate(FEATURE_COLS)
        }
        return results, query_vector

    def explain(self, spot_name: str, prefs: UserPrefs) -> list[dict]:
        matches = self.df[self.df["name"] == spot_name]
        if matches.empty:
            raise ValueError(f"Spot not found: {spot_name!r}")
        idx  = matches.index[0]
        qv   = self._build_query_vector(prefs)
        qvs  = self.scaler.transform(qv.reshape(1, -1))[0]
        spot = self.Xs[idx]

        rows = []
        for i, feat in enumerate(FEATURE_COLS):
            q_val   = float(qvs[i])
            s_val   = float(spot[i])
            weight  = float(self.weights[i])
            contrib = float(min(q_val, s_val) * weight)
            rows.append({
                "feature":      FEATURE_LABELS.get(feat, feat),
                "user_value":   round(q_val, 3),
                "spot_value":   round(s_val, 3),
                "rf_weight":    round(weight, 4),
                "contribution": round(contrib, 4),
            })
        return sorted(rows, key=lambda r: r["contribution"], reverse=True)

    def all_spots(self) -> list[dict]:
        return json.loads(DATA_JSON.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Rate limiter — 60 requests/minute per IP
# ---------------------------------------------------------------------------

limiter = Limiter(key_func=get_remote_address, default_limits=["60/minute"])

# ---------------------------------------------------------------------------
# App + lifespan
# ---------------------------------------------------------------------------

rec = Recommender()

@asynccontextmanager
async def lifespan(app: FastAPI):
    rec.load()
    yield
    logger.info("Shutting down — total requests served: %d", _counters["total"])

app = FastAPI(
    title="UCLA Study Spot Recommender API",
    description=(
        "Content-based study spot recommender using RF-weighted KNN. "
        "Given user preferences, returns ranked UCLA study spots with "
        "similarity scores and per-feature explanations."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Middleware — log every request with method, path, status, and latency
# ---------------------------------------------------------------------------

@app.middleware("http")
async def log_requests(request: Request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    ms = (time.perf_counter() - start) * 1000
    _counters["total"] += 1
    logger.info(
        "%s %s → %d  (%.1f ms)",
        request.method, request.url.path, response.status_code, ms,
    )
    return response

# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", summary="Liveness check")
def health():
    """Returns 200 if the process is running."""
    return {"status": "ok", "spots_loaded": len(rec.df) if rec.df is not None else 0}


@app.get("/ready", summary="Readiness check")
def ready():
    """Returns 200 only if the model is fully loaded and can serve requests."""
    if rec.df is None or rec.Xw is None:
        raise HTTPException(status_code=503, detail="Model not yet loaded")
    try:
        test_prefs = UserPrefs()
        rec.recommend(test_prefs)
    except Exception as e:
        logger.error("Readiness check failed: %s", e)
        raise HTTPException(status_code=503, detail=f"Model check failed: {e}")
    return {"status": "ready", "spots_loaded": len(rec.df)}


@app.get("/stats", response_model=StatsResponse, summary="Usage statistics")
def stats():
    """Returns request counts and uptime since last server start."""
    return StatsResponse(
        uptime_seconds=round(time.time() - _start_time, 1),
        total_requests=_counters["total"],
        recommend_calls=_counters["recommend"],
        explain_calls=_counters["explain"],
        spots_calls=_counters["spots"],
        spots_loaded=len(rec.df) if rec.df is not None else 0,
    )


@app.get("/spots", summary="All study spots")
@limiter.limit("60/minute")
def get_spots(request: Request):
    """Return all 30 spots with full display metadata."""
    _counters["spots"] += 1
    return rec.all_spots()


@app.post("/recommend", response_model=RecommendResponse, summary="Get recommendations")
@limiter.limit("30/minute")
def recommend(prefs: UserPrefs, request: Request):
    """
    Return top-N study spot recommendations ranked by cosine similarity
    in the RF-weighted feature space.

    All fields are optional — omitting them applies sensible defaults.
    """
    _counters["recommend"] += 1
    t0 = time.perf_counter()
    try:
        results, query_vector = rec.recommend(prefs)
    except Exception as e:
        logger.error("Recommendation failed: %s", e)
        raise HTTPException(status_code=500, detail="Recommendation error")
    latency_ms = round((time.perf_counter() - t0) * 1000, 2)
    logger.info(
        "recommend | n=%d noise_tol=%d outdoor=%d quiet=%d → top=%s (%.1f ms)",
        prefs.n_results, prefs.noise_tolerance, prefs.wants_outdoor,
        prefs.wants_quiet, results[0]["name"] if results else "none", latency_ms,
    )
    return RecommendResponse(
        results=results, query_vector=query_vector, latency_ms=latency_ms
    )


@app.post("/recommend/explain", response_model=ExplainResponse, summary="Explain a recommendation")
@limiter.limit("30/minute")
def explain(req: ExplainRequest, request: Request):
    """
    Return a per-feature contribution breakdown showing why a specific spot
    was recommended for a given set of user preferences.
    """
    _counters["explain"] += 1
    try:
        contribs = rec.explain(req.spot_name, req.prefs)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        logger.error("Explain failed for %r: %s", req.spot_name, e)
        raise HTTPException(status_code=500, detail="Explanation error")
    return ExplainResponse(spot_name=req.spot_name, contributions=contribs)